server:
  port: 8081

spring:
  application:
    name: jwt-auth-server
    description: JWT Auth Server
    version: @project.version@

  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username : root
    password : password
  jpa:
    hibernate :
#      ddl-auto : create
      show-sql : true

jwt:
  secret: secretkey123